config/routes.rb
Rails.application.routes.draw do

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  delete '/signout' => 'sessions#destroy'

  get '/admin' => 'admin#index'
  get '/admin/export_attendees' => 'admin#export_attendees'
  get '/admin/edit_mark_as_paid' => 'attendees#edit_mark_as_paid'
  get '/admin/list_all' => 'attendees#list_all'
  get '/admin/edit_attendee' => 'attendees#edit'
  patch '/admin/update_attendee' => 'attendees#update'
  post '/admin/update_mark_as_paid' => 'attendees#update_mark_as_paid'

  scope '(:locale)', :locale => /en|sv/, defaults: {locale: 'sv'} do
    root 'static_pages#home'
    get '/history' => 'static_pages#history'
    get '/menu' => 'static_pages#menu'
    get '/program' => 'static_pages#program'
    get '/medalj' => 'static_pages#medalj'
    get '/faq' => 'static_pages#faq'
    get '/anmalan' => 'attendees#new'
    get '/anmalda' => 'attendees#list_paid'
    post '/anmalan' => 'attendees#create'
    resources :attendees, only: [:show]
  end

end

app/views/admin/index.html.erb
<div id="main">
  <h1>Admin</h1>
  <p>
    Det är för närvarande <b> <%= @registrations %> </b> personer anmälda till
    Höstblotet.<br>
    <b><%= @registrations - @attendees_not_paid.length %></b> av dem har betalat
    in.<br>
    <b><%= @reserves %></b> personer står på reserv-lista.
  </p>
  <p>
    <%= button_to "Exportera anmälda", admin_export_attendees_path(format: :xlsx), method: :get, form_class: "export-form" %>
  </p>
  <p>
    <%= button_to "Uppdatera anmälda", admin_list_all_path, method: :get %>
  </p>
  <% if @attendees_not_paid.empty? %>
    <p>
      Inga nya registreringar har tillkommit.
    </p>
  <% else %>
    <p>
      Följande deltagare saknar registrerad betalning:
    </p>
    <%= form_for :attendee, url: admin_edit_mark_as_paid_path,
                 :html => { :method => :get } do |f| %>
      <table>
        <tr>
          <th>Refnbr</th>
          <th>Pris</th>
          <th>Namn</th>
          <th>Email</th>
          <th>Har betalat</th>
        </tr>
        <% @attendees_not_paid.each do |a| %>
          <tr>
            <td><%= a.refnbr %></td>
            <td><%= a.preference.get_price[:total_price] %> kr</td>
            <td><%= a.name %></td>
            <td><%= a.email %></td>
            <td><%= check_box_tag "attendee_ids[]", a.id, false, id: ('attendee_id_' + a.id.to_s) %></td>
          </tr>
        <% end %>
      </table>
      <p><%= f.submit "Registrera betalning" %></p>
    <% end %>
  <% end %>
</div>