config/routes.rb
Rails.application.routes.draw do

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  delete '/signout' => 'sessions#destroy'

  get '/admin' => 'admin#index'
  get '/admin/export_attendees' => 'admin#export_attendees'
  get '/admin/edit_mark_as_paid' => 'attendees#edit_mark_as_paid'
  get '/admin/list_all' => 'attendees#list_all'
  get '/admin/edit_attendee' => 'attendees#edit'
  patch '/admin/update_attendee' => 'attendees#update'
  post '/admin/update_mark_as_paid' => 'attendees#update_mark_as_paid'

  scope '(:locale)', :locale => /en|sv/, defaults: {locale: 'sv'} do
    root 'static_pages#home'
    get '/history' => 'static_pages#history'
    get '/menu' => 'static_pages#menu'
    get '/program' => 'static_pages#program'
    get '/medalj' => 'static_pages#medalj'
    get '/faq' => 'static_pages#faq'
    get '/anmalan' => 'attendees#new'
    get '/anmalda' => 'attendees#list_paid'
    post '/anmalan' => 'attendees#create'
    resources :attendees, only: [:show]
  end

end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
  has_one :preference, dependent: :destroy
  has_one :foodpreference, dependent: :destroy
  accepts_nested_attributes_for :preference
  accepts_nested_attributes_for :foodpreference

  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true,
    format: { with: VALID_EMAIL_REGEX }
  validates :phone, presence: true
  validates :address, presence: true
  validates :pnbr, presence: true,
    length: {is: 10, message: "format YYMMDDXXXX"}, uniqueness: true
  validates :status, inclusion: {in: ['attending', 'reserve', 'removed']}
  validates :previous_visits, numericality: {allow_blank: true}

  validates :preference, presence: true
  validates :foodpreference, presence: true

  before_save {self.email = email.downcase}
  before_create :generate_refnbr

  def row_color
    if self.status == 'reserve'
      :none
    elsif self.paid
      :green
    else
      :red
    end
  end

  protected

  def generate_refnbr
    range = 10000..100000
    self.refnbr = loop do
      random_refnbr = rand(range)
      break random_refnbr.to_s unless Attendee.exists?(refnbr: random_refnbr.to_s)
    end
  end

end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  before_action :signed_in_user, except: [:new, :create, :list_paid]
  include AttendeeHelper

  def show
    @attendee = Attendee.find(params[:id])
  end

  def new
    if session[:attendee_id]
      @attendee = Attendee.find(session[:attendee_id])
      @is_giver = @attendee.preference.ticket_type.to_sym == :giver
      session.delete(:attendee_id)
      if @attendee.status == 'reserve'
        render 'reserve'
      else
        render 'show'
      end
    else
      @attendee = Attendee.new
      @attendee.build_preference
      @attendee.build_foodpreference
    end
  end

  def create
    @attendee = Attendee.new(new_attendee_params)
    if sexa_cutoff_limit_reached
      @attendee.preference.sexa = false
    end
    if @attendee.save
      if use_reserve_list
        @attendee.update_attribute(:status, 'reserve')
        AttendeeMailer.reserve(@attendee).deliver
        AttendeeMailer.organizer_reserve(@attendee).deliver
      else
        AttendeeMailer.attendee(@attendee).deliver_now
        AttendeeMailer.organizer(@attendee).deliver_now
      end
      if sexa_limit_reached
        AttendeeMailer.sexa_limit_notice.deliver
      end
      session[:attendee_id] = @attendee.id
      redirect_to url_for({controller: 'attendees', action: 'new'})
    else
      render 'new'
    end
  end

  def edit_mark_as_paid
    if params.has_key?(:attendee_ids)
      @attendees_confirm = Attendee.find(params[:attendee_ids])
    else
      redirect_to url_for({controller: 'admin', action: 'index'})
    end
  end

  def update_mark_as_paid
    @attendees_updated = Attendee.find(params[:attendee_ids])
    @attendees_updated.each do |a|
      a.update_attribute(:paid, true)
      AttendeeMailer.paid_notice(a).deliver
    end
  end

  def list_paid
    @attendees = Attendee.where(paid: true, status: 'attending').order(:name)
  end

  def list_all
    @attendees = Attendee.all.order(:status, :name)
  end

  def edit
    @attendee = Attendee.find(params[:id])
  end

  def update
    @attendee = Attendee.find(params[:attendee][:id])
    if @attendee.update_attributes(edit_attendee_params)
      flash[:success] = "Deltagaren är nu uppdaterad"
      redirect_to controller: 'attendees', action: 'list_all'
    else
      render 'edit'
    end
  end

  private

  def new_attendee_params
    params.require(:attendee).permit(:name,:pnbr,:email,:address,:phone,
      :title,:companion, :previous_visits,
      preference_attributes: [:ticket_type,:alcohol,:sexa,:booklet,:medal,:lunch],
      foodpreference_attributes: [:vegan,:vegetarian,:gluten,:lactose,:other])
  end

  def edit_attendee_params
    params.require(:attendee).permit(:id,:name,:pnbr,:email,:address,:phone,
      :title,:companion,:status, :previous_visits,
      preference_attributes: [:id,:ticket_type,:alcohol,:sexa,:booklet,:medal,:lunch],
      foodpreference_attributes: [:id,:vegan,:vegetarian,:gluten,:lactose,:other])
  end

end

app/helpers/attendee_helper.rb
module AttendeeHelper
  @@attendee_limit = 300
  @@sexa_limit = 165
  @@sexa_cutoff_limit = 175

  cattr_reader :sexa_limit

  def attendee_limit_reached
    Attendee.where.not(status: 'removed').count > @@attendee_limit
  end

  def use_reserve_list
    attendee_limit_reached or Time.zone.parse("2019-11-01").past?
  end

  def sexa_limit_reached
    Attendee.where(status: 'attending')
            .joins(:preference)
            .where(preferences: {sexa: true}).count == @@sexa_limit
  end

  def sexa_cutoff_limit_reached
    Attendee.where(status: 'attending')
            .joins(:preference)
            .where(preferences: {sexa: true}).count >= @@sexa_cutoff_limit
  end
end

app/views/attendees/edit.html.erb
<%= render 'shared/error_messages' %>
<div id="main">
  <h1>Uppdatera deltagare</h1>
   <%= form_for @attendee, url: {action: "update"} do |f| %>
    <div style="width:50%;float:left">
      <%= f.hidden_field :id %>
      <%= f.label :name %>: <br>
      <%= f.text_field :name %><br>
      <%= f.label :pnbr, 'Personnummer (ÅÅMMDDXXXX)' %>: <br>
      <%= f.text_field :pnbr %><br>
      <%= f.label :email %>: <br>
      <%= f.email_field :email %><br>
      <%= f.label :address %>: <br>
      <%= f.text_area :address %><br>
      <%= f.label :phone %>: <br>
      <%= f.text_field :phone %><br>
      <%= f.label :title %>: <br>
      <%= f.text_field :title %><br>
      <%= f.label :companion %>: <br>
      <%= f.text_field :companion %><br>
      <%= f.label :status_attending, 'Deltar i höstblotet:' %>
      <%= f.radio_button :status, 'attending' %><br>
      <%= f.label :status_reserve, 'Reservlista:' %>
      <%= f.radio_button :status, 'reserve' %><br>
      <%= f.label :status_removed, 'Kommer ej på balen:' %>
      <%= f.radio_button :status, 'removed' %><br>
      <p>
        <%= f.submit "Uppdatera deltagare"%>
      </p>
    </div>
    <div style="width:50%;float:right">
      <h3 style="margin-top:0px;">Beställning:</h3>
      <%= f.fields_for :preference do |p| %>
        <%= p.hidden_field :id %>
        <p>
          Studerande (<%= Preference.prices[:student] %> kr)
          <%= p.radio_button :ticket_type, :student %><br>
          Ickestuderande
          (<%= Preference.prices[:non_student] %> kr):
          <%= p.radio_button :ticket_type, :non_student %><br>
          Tjänsteman på Blekingska
          (<%= Preference.prices[:active] %> kr):
          <%= p.radio_button :ticket_type, :active %><br>
          Gynnare (<%= Preference.prices[:giver] %> kr)
          <%= p.radio_button :ticket_type, :giver %><br>
        </p>
        <p>
          Alkohol, under middagen
          (<%= Preference.prices[:alcohol] %> kr):
          <%= p.radio_button :alcohol, 'true' %><br>
          Alkoholfritt, under middagen
          (0 kr):
          <%= p.radio_button :alcohol, 'false' %><br>
        </p>
        Sexa (<%= Preference.prices[:sexa] %> kr):
        <%= p.check_box :sexa %><br>
        Sångbok (<%= Preference.prices[:booklet] %> kr):
        <%= p.check_box :booklet %><br>
        Ballunch (<%= Preference.prices[:lunch] %> kr):
        <%= p.check_box :lunch %><br>
        <p>
          Medalj (<%= Preference.prices[:medal] %> kr):
          <%= p.radio_button :medal, 'yes' %><br>
          Medalj, inbyte (<%= Preference.prices[:trade_in] %> kr):
          <%= p.radio_button :medal, 'trade_in' %><br>
          Ingen medalj (0 kr):
          <%= p.radio_button :medal, 'no' %><br>
          Tidigare antal höstblot: <%= f.text_field :previous_visits,
                                                    maxlength: "3",
                                                    class: "numberfield" %><br>
        </p>
      <% end %>
      <h3>Matpreferenser:</h3>
      <%= f.fields_for :foodpreference do |fp| %>
        <%= fp.hidden_field :id %>
        <p>
          Vegetarian: <%= fp.check_box :vegetarian %><br>
          Vegan: <%= fp.check_box :vegan %><br>
        </p>
        Glutenfritt: <%= fp.check_box :gluten %><br>
        Laktosfritt: <%= fp.check_box :lactose %><br>
        Övriga Matpreferenser:<br>
        <%= fp.text_area :other %><br>
      <% end %>
    </div>
  <% end %>
</div>

app/views/attendees/edit_mark_as_paid.html.erb
<div id="main">
  <p>
    Du är nu på väg att bekräfta att följande baldeltagare har betalat in: <br>
  </p>
  <%= form_for :attendee, url: admin_update_mark_as_paid_path,
                 :html => { :method => :post } do |f| %>
    <% for a in @attendees_confirm %>
      <%= hidden_field_tag "attendee_ids[]", a.id %>
    <% end %>
    <table>
      <tr>
        <th>Refnbr</th>
        <th>Pris</th>
        <th>Namn</th>
        <th>Email</th>
      </tr>
      <% @attendees_confirm.each do |a| %>
        <tr>
          <td><%= a.refnbr %></td>
          <td><%= a.preference.get_price[:total_price] %> kr</td>
          <td><%= a.name %></td>
          <td><%= a.email %></td>
        </tr>
      <% end %>
    </table>
    <p>
      Dessa deltagare kommer att få ett bekräftelsemail på att de har betalat in
      till Höstblotet.
    </p>
    <p>
      Är du säker på att du vill utföra denna handling?
    </p>
    <%= f.submit "Ja", style:"float:left" %>
  <% end %>
  <%= button_to "Avbryt", {controller: 'admin', action: 'index'},
                style:"float:rigth;margin-left:10px;", method: :get %>
</div>

app/views/attendees/list_all.html.erb
<div id="main">
  <h1>Uppdatera deltagare</h1>
    <table>
      <tr>
        <th>Namn</th>
        <th>Titel</th>
        <th>Email</th>
        <th>Status</th>
        <th>Uppdatera</th>
      </tr>
      <% @attendees.each do |a| %>
        <tr>
          <td><%= a.name %></td>
          <td><%= a.title %></td>
          <td><%= a.email %></td>
          <% if a.status == 'attending' %>
            <td>Kommer</td>
          <% elsif a.status == 'reserve' %>
            <td>Reserv</td>
          <% elsif a.status == 'removed' %>
            <td>Kommer EJ</td>
          <% end %>
          <td style="text-align:center;"><%= link_to "Uppdatera",
            {controller: 'attendees', action: 'edit', id: a.id} %></td>
        </tr>
      <% end %>
    </table>
</div>

app/views/attendees/list_paid.en.html.erb
<% provide(:title, t(:attendees)) %>
<div id="main">
  <h1><%= t(:attendees) %></h1>

  <p>
    The following people have signed up and confirmed:
  </p>

  <% if @attendees.empty? %>
    <p>
      No attendees confirmed yet.
    </p>
  <% else %>
    <table>
    <tr>
      <th>Name</th>
      <th>Title</th>
    </tr>
      <% @attendees.each do |a| %>
        <tr>
          <td><%= a.name %></td>
          <td><%= a.title %></td>
        </tr>
      <% end %>
    </table>
  <% end %>
</div>

app/views/attendees/list_paid.html.erb
<% provide(:title, t(:attendees)) %>
<div id="main">
  <h1><%= t(:attendees) %></h1>

  <p>
    Följande personer är anmälda och bekräftade:
  </p>

  <% if @attendees.empty? %>
    <p>
      Inga personer är bekräftade än.
    </p>
  <% else %>
    <table>
    <tr>
      <th>Namn</th>
      <th>Titel</th>
    </tr>
      <% @attendees.each do |a| %>
        <tr>
          <td><%= a.name %></td>
          <td><%= a.title %></td>
        </tr>
      <% end %>
    </table>
  <% end %>
</div>

app/views/attendees/new.en.html.erb
<%= render 'shared/error_messages' %>
<div id="main">
<% if false %>
  <h1>Sign up closed!</h1>
  <p>
    Did you miss your chance to get a ticket? Send an e-mail to
    <a href="mailto:bal@blekingska.se">bal@blekingska.se</a> and we will
    see what we can do!
  </p>
<% else %>
  <% if use_reserve_list %>
    <% provide(:title, t(:reserve_list)) %>
    <h1><%= t(:reserve_list) %></h1>
    <p class="bold">
      Attention! This is only a registration form for the reserve list, as we
      have reached the limit of maximum attendees. If a place is freed, we will
      contact you with further information.
    </p>
  <% else %>
    <% provide(:title, t(:signup)) %>
    <h1><%= t(:signup) %></h1>
    <p style="text-align:center">
      <em>Last payment and registration day is the 31th of October.</em>
    </p>
  <% end %>
  <%= form_for @attendee, url: {action: "create", locale: I18n.locale} do |f| %>
    <div class="attending-form attending-form-primary">
      <%= f.label :name %><br>
      <%= f.text_field :name %><br>
      <%= f.label :pnbr, 'Personal number (YYMMDDXXXX)' %><br>
      <%= f.text_field :pnbr %><br>
      <%= f.label :email %><br>
      <%= f.email_field :email %><br>
      <%= f.label :address %><br>
      <%= f.text_area :address %><br>
      <%= f.label :phone %><br>
      <%= f.text_field :phone %><br>
      <%= f.label :title %><br>
      <%= f.text_field :title %><br>
      <%= f.label :companion %><br>
      <%= f.text_field :companion %><br>
      <p class="form-info">
        Make sure that your companion also signs up separately.
        This field has limited influence over the seating arrangements.
        <br>
        Blekingska nationen i Lund collects this data when a ball ticket is
        purchased for the purpose of planning Höstblotet, e.g. with regards to
        the seating arrangements, and to stay in contact with the participants
        before and after the ball. More information is available in the
        nation’s Integrity Policy (in Swedish) which you can find here:
        <a href="https://www.blekingska.se/policyer">blekingska.se/policyer</a>.
        If you have further questions or want us to delete your data, please
        contact <a href="mailto:q@blekingska.se">q@blekingska.se</a>.
      </p>
    </div>
    <div class="attending-form attending-form-secondary">
      <%= f.fields_for :preference do |p| %>
        <p>
          <%= p.radio_button :ticket_type, :student %>
          <label for="attendee_preference_attributes_ticket_type_student">Student <span>(<%= Preference.prices[:student] %> kr)</span></label><br>
          <%= p.radio_button :ticket_type, :non_sudent %>
          <label for="attendee_preference_attributes_ticket_type_non_student">Non student <span>(<%= Preference.prices[:non_student] %> kr)</span></label><br>
          <%= p.radio_button :ticket_type, :active %>
          <label for="attendee_preference_attributes_ticket_type_active">Tjänsteman at Blekingska <span>(<%= Preference.prices[:active] %> kr)</span></label><br>
          <%= p.radio_button :ticket_type, :giver %>
          <label for="attendee_preference_attributes_ticket_type_giver">Giver <span>(<%= Preference.prices[:giver] %> kr or more)</span></label><br>
        </p>
        <p>
          <%= p.radio_button :alcohol, true %>
          <label for="attendee_preference_attributes_alcohol_true">Alcohol during dinner <span>(<%= Preference.prices[:alcohol] %> kr)</span></label><br>
          <%= p.radio_button :alcohol, false %>
          <label for="attendee_preference_attributes_alcohol_false">No alcohol during dinner <span>(0 kr)</span></label><br>
        </p>
        <p>
          <%= p.check_box :sexa, disabled: sexa_cutoff_limit_reached %>
          <% if sexa_cutoff_limit_reached %>
            <label for="attendee_preference_attributes_sexa"><s>Sexa <span>(<%= Preference.prices[:sexa] %> kr)</span></s> No places left</label><br>
          <% else %>
            <label for="attendee_preference_attributes_sexa">Sexa <span>(<%= Preference.prices[:sexa] %> kr)</span></label><br>
          <% end %>
          <%= p.check_box :booklet %>
          <label for="attendee_preference_attributes_booklet">Songbook <span>(<%= Preference.prices[:booklet] %> kr)</span></label><br>
          <%= p.check_box :lunch %>
          <label for="attendee_preference_attributes_lunch">Bal lunch <span>(<%= Preference.prices[:lunch] %> kr)</span></label><br>
        </p>
        <p>
          <%= p.radio_button :medal, 'yes' %>
          <label for="attendee_preference_attributes_medal_yes">Medal <span>(<%= Preference.prices[:medal] %> kr)</span></label><br>
          <%= p.radio_button :medal, 'trade_in' %>
          <label for="attendee_preference_attributes_medal_trade_in">Medal, trade-in <span>(<%= Preference.prices[:trade_in] %> kr)</span></label><br>
          <%= p.radio_button :medal, 'no' %>
          <label for="attendee_preference_attributes_medal_no">No medal <span>(0 kr)</span></label><br>
          <label for="attendee_previous_visits">Nbr. of previous Höstblot:</label>
          <%= f.text_field :previous_visits, maxlength: "3", class: "numberfield" %><br>
        </p>
      <% end %>
      <%= f.fields_for :foodpreference do |fp| %>
        <p>
          <%= fp.check_box :vegetarian %>
          <label for="attendee_foodpreference_attributes_vegetarian">Vegetarian</label>
          <br>
          <%= fp.check_box :vegan %>
          <label for="attendee_foodpreference_attributes_vegan">Vegan</label>
          <br>
        </p>
        <p>
          <%= fp.check_box :gluten %>
          <label for="attendee_foodpreference_attributes_gluten">Gluten free</label><br>
          <%= fp.check_box :lactose %>
          <label for="attendee_foodpreference_attributes_lactose">Lactose free</label><br>
        </p>
        <p>
          <label for="attendee_foodpreference_attributes_other">Other food preferences:</label><br>
          <%= fp.text_area :other %><br>
        </p>
      <% end %>
      <p class="signup-button">
        <%= f.submit "Sign up!"%>
      </p>
    </div>
  <% end %>
<% end %>
</div>

app/views/attendees/new.html.erb
<%= render 'shared/error_messages' %>
<div id="main">
<% if false %>
  <h1>Anmälan stängd!</h1>
  <p>
    Missade du att köpa din biljett? Maila
    <a href="mailto:bal@blekingska.se">bal@blekingska.se</a>
    så gör vi vårt bästa för att du skall kunna gå på balen!
  </p>
<% else %>
  <% if use_reserve_list %>
    <% provide(:title, t(:reserve_list)) %>
    <h1><%= t(:reserve_list) %></h1>
    <p class="bold">
      Observera! Detta är endast en anmälan till reservlista, då balens
      deltagarlista är full. Vi kontaktar dig om en plats eventuellt öppnar sig.
    </p>
  <% else %>
    <% provide(:title, t(:signup)) %>
    <h1><%= t(:signup) %></h1>
    <p style="text-align:center">
      <em>Sista anmälnings- och betalningsdag är 31e oktober.</em>
    </p>
  <% end %>
  <%= form_for @attendee, url: {action: "create", locale: I18n.locale} do |f| %>
    <div class="attending-form attending-form-primary">
      <%= f.label :name %><br>
      <%= f.text_field :name %><br>
      <%= f.label :pnbr, 'Personnummer (ÅÅMMDDXXXX)' %><br>
      <%= f.text_field :pnbr %><br>
      <%= f.label :email %><br>
      <%= f.email_field :email %><br>
      <%= f.label :address %><br>
      <%= f.text_area :address %><br>
      <%= f.label :phone %><br>
      <%= f.text_field :phone %><br>
      <%= f.label :title %><br>
      <%= f.text_field :title %><br>
      <%= f.label :companion %><br>
      <%= f.text_field :companion %><br>
      <p class="form-info">
        Glöm inte att ditt ev. följe även måste anmäla sig separat!
        Denna ruta har begränsat inflytande på bordsplaceringen.
        <br>
        Blekingska nationen i Lund samlar in dessa personuppgifter i samband
        med köp av balbiljett för att planera Höstblotet med exempelvis
        bordsplacering och för att kunna hålla kontakten med deltagarna före
        och efter baldagen. Mer information finns i nationens integritetspolicy
        som du kan hitta här: <a href="https://www.blekingska.se/policyer">blekingska.se/policyer</a>.
        Vid frågor eller för att begära att uppgifterna om dig raderas, kontakta
        <a href="mailto:q@blekingska.se">q@blekingska.se</a>.
      </p>
    </div>
    <div class="attending-form attending-form-secondary">
      <%= f.fields_for :preference do |p| %>
        <p>
          <%= p.radio_button :ticket_type, :student %>
          <label for="attendee_preference_attributes_ticket_type_student">Studerande <span>(<%= Preference.prices[:student] %> kr)</span></label><br>
          <%= p.radio_button :ticket_type, :non_student %>
          <label for="attendee_preference_attributes_ticket_type_non_student">Icke-studerande <span>(<%= Preference.prices[:non_student] %> kr)</span></label><br>
          <%= p.radio_button :ticket_type, :active %>
          <label for="attendee_preference_attributes_ticket_type_active">Tjänsteman på Blekingska <span>(<%= Preference.prices[:active] %> kr)</span></label><br>
          <%= p.radio_button :ticket_type, :giver %>
          <label for="attendee_preference_attributes_ticket_type_giver">Gynnare <span>(<%= Preference.prices[:giver] %> kr eller mer)</span></label><br>
        </p>
        <p>
          <%= p.radio_button :alcohol, true %>
          <label for="attendee_preference_attributes_alcohol_true">Alkohol till maten <span>(<%= Preference.prices[:alcohol] %> kr)</span></label><br>
          <%= p.radio_button :alcohol, false %>
          <label for="attendee_preference_attributes_alcohol_false">Alkoholfritt till maten <span>(0 kr)</span></label><br>
        </p>
        <p>
          <%= p.check_box :sexa, disabled: sexa_cutoff_limit_reached %>
          <% if sexa_cutoff_limit_reached %>
            <label for="attendee_preference_attributes_sexa"><s>Sexa <span>(<%= Preference.prices[:sexa] %> kr)</span></s> Fullsatt</label><br>
          <% else %>
            <label for="attendee_preference_attributes_sexa">Sexa <span>(<%= Preference.prices[:sexa] %> kr)</span></label><br>
          <% end %>
          
          <%= p.check_box :booklet %>
          <label for="attendee_preference_attributes_booklet">Sångbok <span>(<%= Preference.prices[:booklet] %> kr)</span></label><br>
      
          <%= p.check_box :lunch %>
          <label for="attendee_preference_attributes_lunch">Ballunch <span>(<%= Preference.prices[:lunch] %> kr)</span></label><br>
        </p>
        <p>
          <%= p.radio_button :medal, 'yes' %>
          <label for="attendee_preference_attributes_medal_yes">Medalj <span>(<%= Preference.prices[:medal] %> kr)</span></label><br>
          <%= p.radio_button :medal, 'trade_in' %>
          <label for="attendee_preference_attributes_medal_trade_in">Medalj, inbyte <span>(<%= Preference.prices[:trade_in] %> kr)</span></label><br>
          <%= p.radio_button :medal, 'no' %>
          <label for="attendee_preference_attributes_medal_no">Ingen medalj <span>(0 kr)</span></label><br>
          <label for="attendee_previous_visits">Tidigare antal Höstblot:</label>
          <%= f.text_field :previous_visits, maxlength: "3", class: "numberfield" %>
        </p>
      <% end %>
      <%= f.fields_for :foodpreference do |fp| %>
        <p>
          <%= fp.check_box :vegetarian %>
          <label for="attendee_foodpreference_attributes_vegetarian">Vegetarian</label>
          <br>
          <%= fp.check_box :vegan %>
          <label for="attendee_foodpreference_attributes_vegan">Vegan</label>
          <br>
        </p>
        <p>
          <%= fp.check_box :gluten %>
          <label for="attendee_foodpreference_attributes_gluten">Glutenfritt</label><br>
          <%= fp.check_box :lactose %>
          <label for="attendee_foodpreference_attributes_lactose">Laktosfritt</label><br>
        </p>
        <p>
          <label for="attendee_foodpreference_attributes_other">Övriga matpreferenser</label><br>
          <%= fp.text_area :other %><br>
        </p>
      <% end %>
      <p class="signup-button">
        <%= f.submit "Anmäl mig!"%>
      </p>
    </div>
  <% end %>
<% end %>
</div>

app/views/attendees/update_mark_as_paid.html.erb
<div id="main">
  <p>
    Följande deltagare har nu fått sin inbetalning registrerad: <br>
  </p>
  <table>
    <tr>
      <th>Refnbr</th>
      <th>Namn</th>
      <th>Email</th>
      <th>Pris</th>
    </tr>
    <% @attendees_updated.each do |a| %>
      <tr>
        <td><%= a.refnbr %></td>
        <td><%= a.name %></td>
        <td><%= a.email %></td>
        <td><%= a.preference.get_price[:total_price] %> kr</td>
      </tr>
    <% end %>
  </table>
  <p>
    Bekräftelsemail är nu påväg till dessa deltagare.
  </p>
  <div>
    <%= button_to "Tillbaka", {controller: 'admin', action: 'index'},
                  method: :get %>
  </div>
</div>